fail_fast: true
repos:
  - repo: local
    hooks:
      - id: linter
        name: linter
        entry: poetry run ruff check
        language: system
        types: [file, python]
      - id: formatter
        name: formatter
        entry: poetry run ruff format
        language: system
        types: [file, python]