name: "Automatic release"

on:
  workflow_dispatch:

jobs:
  publish_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
      - name: Install dev dependencies
        run: poetry install

      - name: Get latest unreleased bun version
        run: poetry run python src/get_unreleased_bun_version.py

      - name: We have an unreleased bun version
        if: ${{ hashFiles('LATEST_UNRELEASED_BUN_VERSION.txt') != '' }}
        run: cat LATEST_UNRELEASED_BUN_VERSION.txt
      
      - name: We are up to date
        if: ${{ hashFiles('LATEST_UNRELEASED_BUN_VERSION.txt') = '' }}
        run: echo "We are up to date"
